apiVersion : apps/v1
kind: Deployment
metadata:
  name: ekstest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new 
    spec:
      containers:
        - name: ekstest 
          image: gurudevopsacr.azurecr.io/new
          ports:

          - containerPort: 80
